/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xue_song_fmod_PlayQQEffectActivity */

#ifndef _Included_com_xue_song_fmod_PlayQQEffectActivity
#define _Included_com_xue_song_fmod_PlayQQEffectActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xue_song_fmod_PlayQQEffectActivity
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xue_song_fmod_PlayQQEffectActivity_init
  (JNIEnv *, jobject,jstring);

/*
 * Class:     com_xue_song_fmod_PlayQQEffectActivity
 * Method:    playSound
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xue_song_fmod_PlayQQEffectActivity_playSound
  (JNIEnv *, jobject, jint,jstring);

#ifdef __cplusplus
}
#endif
#endif
